import { makeStyles } from "@material-ui/core"
import { theme } from "../../components/ui/theme"
export const useStyle = makeStyles({
    fitContent:{
        width:"fit-content",
    },
    PageContainer:{
        [theme.breakpoints.down("sm")]:{
            padding:"0 .8rem"
        }
    },
    headerResp:{
        [theme.breakpoints.down("md")]:{
            textAlign:"center"
        },
        [theme.breakpoints.down("sm")]:
        {fontSize:"2em",marginBottom:".7rem",textAlign:"center"},
        [theme.breakpoints.down("xs")]:
        {fontSize:"1.8em"},
    },
    marginLeft:{
        marginLeft:"3rem",
        [theme.breakpoints.down('sm')]:{
            margin:"auto"
        }
    },
    marginRight:{
        marginRight:"3rem",
        [theme.breakpoints.down('sm')]:{
            margin:"auto"
        },
    },
    subResp:{
        "& > *":{
            [theme.breakpoints.down('sm')]:{
                fontSize:".9em"
            },
            [theme.breakpoints.down('xs')]:{
                fontSize:".8em"
            }
        }
    },
    PageTitle:{
        fontFamily:"Pacifico !important",
        marginBottom:"2rem",
        [theme.breakpoints.down("md")]:{textAlign:"center",margin:"2rem auto"}
    },
    //////////////////////////////////////////////////
    visionText:{
        maxWidth:"40%",
        textAlign:"right",
        [theme.breakpoints.down("md")]:{
            maxWidth:"450px",
            textAlign:"center",
            margin:"auto"
        },
    },
    visionImg:{
        maxWidth:"45%",
        [theme.breakpoints.down("md")]:{
            maxWidth:"auto"
        },
        [theme.breakpoints.down("sm")]:{
            width:"80%"
        }
    },
    marginBottom:{
        '& > *':{
            marginBottom:"1rem"
        }
    },
    visionImgOrigin:{
        maxWidth:"500px",
        [theme.breakpoints.down("md")]:{
            maxWidth:"400px",margin:"1.2rem auto 0"
        },
        [theme.breakpoints.down("sm")]:{
            maxWidth:"260px"
        }    
    },
    //////////////////////////////////////////////////
    RepairText:{
        maxWidth:"40%",
        textAlign:"left",
        [theme.breakpoints.down("md")]:{
            maxWidth:"450px",
            textAlign:"center"
        },
    },
    RepairImgContainer:{
        maxWidth:"50%",
        [theme.breakpoints.down("md")]:{
            maxWidth:"80%",            
        }
    },
    RepairImg:{
        maxWidth:"100px"
    },
///////////////////////////////
    consultationText:{
        width:"210px",
        [theme.breakpoints.down("xs")]:{
            width:"90%",
            textAlign:"center"
        }
    },
    consultationImgContainer:{
        width:"fit-content",
        margin:"auto"
    },
    consultationImg:{
        maxWidth:"30rem",
        [theme.breakpoints.down("md")]:{
            maxWidth:"25rem",
        },
        [theme.breakpoints.down("sm")]:{
            maxWidth:"15rem",
        }
    },
    magnifing:{
        maxWidth:"20rem",
        [theme.breakpoints.down("md")]:{
            maxWidth:"16rem",
        },
        [theme.breakpoints.down("sm")]:{
            maxWidth:"9rem",
        },
    },
    brush:{
        maxWidth:"50rem",
        [theme.breakpoints.down("md")]:{
            maxWidth:"35rem",
        },
        [theme.breakpoints.down("sm")]:{
            maxWidth:"20rem",
        },
    }
})